WIP: Result thingy
fkie-cad/FACT_core pull request #1027
Opened 2023-05-04 11:06 UTC by maringuu

2023-05-15 13:30 UTC, maringuu commented on src/plugins/analysis/architecture_detection/internal/dt.py
> +    for dt_dict in file_object.processed_analysis['device_tree']["result"].get('device_trees', []):
> Also what happened to the "double-quote-string-fixer" pre-commit hook?

Muscle memory to ignore it..

2023-05-15 13:30 UTC, maringuu commented
Converted to draft again as this still has many bugs.

2023-05-31 12:29 UTC, jstucke requested changes

2023-05-31 12:29 UTC, jstucke commented on src/unpacker/unpack.py
> +        )
Wow this is a rare case where breaking the lines actually worsens the readability :sweat_smile: 
```suggestion
        report = Path(tmp_dir) / 'reports/meta.json'
        current_fo.processed_analysis['unpacker'] = sanitize_processed_analysis(json.loads(report.read_text()))
```

2023-06-01 11:29 UTC, maringuu commented on src/storage/entry_conversion.py
> +    return data
> I'm not sure what the function name is supposed to mean#

It's a returning version of the sanitize.

But yeah I agree, it doesn't hurt to let sanitize return.

2023-06-01 12:34 UTC, maringuu commented on src/storage/entry_conversion.py
> +    return data
> I'm not sure what the function name is supposed to mean#

It's a returning version of the sanitize.

But yeah I agree, it doesn't hurt to let sanitize return.

2023-06-05 11:41 UTC, jstucke approved these changes
LGTM!

2023-06-05 13:28 UTC, merged