info leaks: added regex to find credentials in urls
fkie-cad/FACT_core pull request #1177
Opened 2023-11-23 16:41 UTC by jstucke

2024-07-18 09:46 UTC, maringuu requested changes

2024-07-19 09:42 UTC, jstucke commented on src/plugins/analysis/information_leaks/code/information_leaks.py
> +    # based on https://gitlab.com/gitlab-com/gl-security/threatmanagement/redteam/redteam-public/token-hunter regex
done

2024-08-01 15:01 UTC, maringuu commented
I fixed up the comment and cleaned up the history. Regarding code nothing was changed ([diff](https://github.com/fkie-cad/FACT_core/compare/6901a71a29664beaa820e45afc71decb7566a57d..f6fb0d181a70b34828af3b16ddcfb68a50a66e2b)). 

Can you investigate the CI failure?

2024-08-02 06:43 UTC, jstucke commented
> Can you investigate the CI failure?

`test_regression_virtual_file_path` seems to be flaky again :confused: 
I will just restart the CI worker. We are already using a library for flaky tests and maybe we should just add that one :see_no_evil:

2024-08-08 07:24 UTC, maringuu approved these changes

2024-08-08 07:24 UTC, merged