Graphql search
fkie-cad/FACT_core pull request #1269
Opened 2024-09-24 09:08 UTC by jstucke

2024-10-30 15:04 UTC, dorpvom requested changes

2024-10-30 15:07 UTC, dorpvom commented
Also: Where are the tests?

2024-10-30 15:46 UTC, jstucke commented
> Also: Where are the tests?

a test file was missing (see https://github.com/fkie-cad/FACT_core/pull/1269/commits/4b527866cd2a80081287801654be27dcbdb4f09a)

2024-10-30 15:49 UTC, jstucke commented on src/storage/graphql/hasura/restart.py
> +import sys
added

2024-10-30 15:49 UTC, jstucke commented on src/storage/graphql/hasura/docker-compose.yaml
> +      HASURA_GRAPHQL_METADATA_DEFAULTS: '{"backend_configs":{"dataconnector":{"athena":{"uri":"http://data-connector-agent:8081/api/v1/athena"},"mariadb":{"uri":"http://data-connector-agent:8081/api/
removed

2024-10-31 09:41 UTC, dorpvom approved these changes

2024-10-31 09:46 UTC, merged