Upload reanalyze template merge
fkie-cad/FACT_core pull request #489
Opened 2020-09-08 12:37 UTC by jstucke

- merged upload and re-analyze templates (>90% identical)
- moved `overwrite_default_plugins()` helper function (only used once)

2020-09-29 15:03 UTC, dorpvom requested changes

2020-09-29 15:03 UTC, dorpvom commented on src/test/unit/web_interface/test_app_re_analyze.py
> +        assert self.mocked_interface.tasks[0].uid == TEST_FW.uid, "fw not added to intercom"
Mix of `'` and `"` quotation

2020-09-29 15:03 UTC, dorpvom commented on src/web_interface/templates/upload/upload.html
> +                        $('#device_name').append('<option>' + 'new entry' + '</option>');
At about this point in the file I now decided to not code review this file further.
I'll make a functional review and leave it at that.

2020-09-30 06:57 UTC, jstucke commented on src/web_interface/templates/upload/upload.html
> +{%- extends "base.html" -%}
The purpose of these is to remove the whitespace when rendering the template.
E.g.
```html
<tag1>
    {% if foo %}
    {% endif %}
        <tag2>
```
would render to
```html
<tag1>


        <tag2>
```
and

```html
<tag1>
    {%- if foo -%}
    {%- endif %}
        <tag2>
```
would render to
```html
<tag1>
        <tag2>
```
Long story short: the source of our templates looks less messy.

2020-09-30 07:06 UTC, jstucke commented on src/web_interface/templates/upload/upload.html
> +                    var device_names = eval( {{ device_names | safe }} );
If I remember correctly, this was done to pass json from jinja to javascript but it turns out it isn't even necessary -> removed

2020-09-30 07:08 UTC, jstucke commented on src/test/unit/web_interface/test_app_re_analyze.py
> +        assert self.mocked_interface.tasks[0].uid == TEST_FW.uid, "fw not added to intercom"
fixed

2020-09-30 08:02 UTC, dorpvom approved these changes

2020-09-30 08:02 UTC, merged