Binary mapping
fkie-cad/FACT_core pull request #519
Opened 2020-11-25 18:34 UTC by Geierhaas

2020-11-26 14:29 UTC, jstucke requested changes
Looks mostly fine. Would it be possible to make the legend "undraggable"?

2020-11-26 14:29 UTC, jstucke commented on src/web_interface/components/dependency_graph.py
> +            link_to = node['full_file_type'].split(' ')[3].split('\'')[1]
Shouldn't 
```suggestion
            link_to = node['full_file_type'].split('\'')[1]
```
work just as well?

2020-11-26 14:29 UTC, jstucke commented on src/web_interface/templates/dependency_graph.html
> +    var get_groups = eval( {{ groups | safe }} )
The `eval()` shouldn't be necessary (and we generally want as few `eval()`s in our code as possible :sweat_smile: )
```suggestion
    var get_nodes = {{ nodes | safe }}
    var get_edges = {{ edges | safe }}
    var get_groups = {{ groups | safe }}
```

2020-11-26 14:29 UTC, jstucke commented on src/web_interface/templates/dependency_graph.html
> +        color_list = {{ color_list | safe }}
It would be a good idea to put `{{ color_list | safe }}` in a variable, so that it doesn't get rendered three times

2020-11-26 14:29 UTC, jstucke commented on src/web_interface/templates/dependency_graph.html
> +    console.log(color_list);
Artifact from debugging?

2020-11-26 14:29 UTC, jstucke commented on src/web_interface/templates/dependency_graph.html
> +    legend_edges.add([]);
Does this do anything?

2020-12-03 10:48 UTC, jstucke commented on src/storage/db_interface_frontend.py
> +            {'parents': uid},
it seems the trailing space in this line displeased the CI:

> 00:25:54 =================================== FAILURES ===================================
00:25:54 _______________________ FLAKE8-check(ignoring E501 W503) _______________________
00:25:54 /home/jenkins/workspace/xenial/src/storage/db_interface_frontend.py:333:30: W291 trailing whitespace

2020-12-03 10:49 UTC, jstucke commented on src/storage/db_interface_frontend.py
> +            {'parents': uid},
```suggestion
            {'parents': uid},
```

2020-12-04 09:57 UTC, jstucke approved these changes

2020-12-09 14:25 UTC, dorpvom commented
Looks all around fine to me. Caveats:
- This produces funny graphs if the elf_analysis is not present for most files.
- The error message, asking to choose another file as root, could be more precise. Which files can be chosen as root?

2020-12-11 14:28 UTC, dorpvom approved these changes

2020-12-11 14:28 UTC, merged