Flask Restx API
fkie-cad/FACT_core pull request #557
Opened 2021-03-27 20:32 UTC by any333

2021-04-26 11:33 UTC, jstucke requested changes

2021-04-26 11:33 UTC, jstucke commented on src/web_interface/rest/rest_firmware.py
> +        List all available firmwares in the database
firmware is not countable (like software): firmwares -> firmware

2021-04-26 11:33 UTC, jstucke commented on src/web_interface/rest/rest_firmware.py
> +        List all available firmwares in the database
Documentation of optional URL arguments (offset, limit, query, recursive and inverted) is missing (see https://github.com/fkie-cad/FACT_core/wiki/Rest-API#get)

2021-04-26 11:33 UTC, jstucke commented on src/web_interface/rest/rest_firmware.py
> +                'params': {'uid': 'File UID'}
'File UID' -> 'Firmware UID'

2021-04-26 11:33 UTC, jstucke commented on src/web_interface/rest/rest_firmware.py
> +    @api.doc(responses={200: 'Success', 400: 'Unknown file object'})
'Unknown file object' -> 'Unknown firmware' or 'Unknown UID'

2021-04-26 11:33 UTC, jstucke commented on src/web_interface/rest/rest_firmware.py
> +        Get a specific file by providing the uid of the corresponding firmware
This is kind of misleading. You don't really get a "file" in the result. It is a firmware entry from the database (converted to JSON).

2021-04-26 11:33 UTC, jstucke commented on src/web_interface/rest/rest_firmware.py
> +        Get a specific file by providing the uid of the corresponding firmware
This is also missing the documentation of an optional URL parameter: "summary"

2021-04-26 11:33 UTC, jstucke commented on src/web_interface/rest/rest_firmware.py
> +        The HTTP body shall contain a json document of the structure shown below
shall -> must
shall sounds very ... archaic (I know it is like this in the REST docs, too. We really need to revise them. Maybe you can update it there, too)

2021-04-26 11:33 UTC, jstucke commented on src/web_interface/rest/rest_firmware.py
> +        You can use this endpoint to update a firmware analysis which is already existing
I think the doc strings of put with and without UID may be switched? (You update a firmware with a UID and upload one without it)

2021-04-26 11:33 UTC, jstucke commented on src/web_interface/rest/rest_missing_analyses.py
> +@api.route('', doc={'description': ''})
you can remove the parameter `doc` if it is empty

2021-04-26 11:33 UTC, jstucke commented on src/web_interface/rest/rest_missing_analyses.py
> +        Search for missing files or missing analyses
This endpoint has some additional functionality that is still missing from the REST docs
```suggestion
        Search for missing or orphaned files and missing or failed analyses
```

2021-04-26 11:33 UTC, jstucke commented on src/web_interface/rest/rest_status.py
> +@api.route('', doc={'description': ''})
see above

2021-04-26 11:33 UTC, jstucke commented on src/web_interface/rest/rest_status.py
> +    @api.doc(responses={200: 'Success', 400: 'Unknown system status'})
'Unknown system status' doesn't really make sense. 'Error' should be fine

2021-06-10 06:45 UTC, dorpvom approved these changes

2021-06-10 07:06 UTC, jstucke approved these changes

2021-06-10 07:06 UTC, merged