Analsysis/Compare: Don't die on failing import
fkie-cad/FACT_core pull request #612
Opened 2021-07-13 15:21 UTC by maringuu

This wraps importing plugins in a try-except block.

Now a plugin can contain invalid code and the fact backend will still start.

2021-07-19 10:09 UTC, jstucke requested changes
Seems to work fine. Some small issues

2021-07-19 10:09 UTC, jstucke commented on src/compare/compare.py
> +                # upgraded to incompatible versions
The dependencies could also simply be missing (either if new dependencies were added and the user did not re-run the installation or if the user didn't install FACT correctly in the first place)

2021-07-19 10:09 UTC, jstucke commented on src/scheduler/Analysis.py
> +            except Exception as e:
see above

2021-07-19 10:09 UTC, jstucke commented on src/scheduler/Analysis.py
> +                logging.error(f'Could not import plugin {plugin_name} due to Exception: {e}')
see above

2021-07-30 07:14 UTC, maringuu commented
Adressed review in #616

2021-07-30 07:14 UTC, closed without merging