Extract apt/dnf and python dependencies in files
fkie-cad/FACT_core pull request #618
Opened 2021-07-30 09:47 UTC by maringuu

The comments that describe the dependencies are just copied over in the `requirements.txt` file.

2021-08-04 12:02 UTC, jstucke requested changes
This definitely needs to run on the CI before merging

2021-08-04 12:07 UTC, jstucke commented on src/helperFunctions/install.py
> +            logging.debug(f"Failed to run {err.cmd}:\n{err.stderr}\n\nIgnoring")
Also, something like "Failed to run (ignored): ..." could be easier to interpret as "Failed to run ... \n\nIgnoring" when looking at the logs

2021-08-06 07:24 UTC, maringuu commented on src/helperFunctions/install.py
> +        subprocess.run(cmd_, capture_output=True, encoding='UTF-8', shell=shell, **kwargs).check_returncode()
Yes! I didn't know about `check`.

2021-08-10 08:21 UTC, jstucke commented on src/helperFunctions/install.py
> +        # Split with shlex to have shell commands work as intendet
Small typo (but I don't know if the comment is really needed -- I think it is pretty self-explanatory)
```suggestion
        # Split with shlex to have shell commands work as intended
```

2021-08-10 11:25 UTC, maringuu commented on src/helperFunctions/install.py
> +            logging.debug(f"Failed to run {err.cmd} (ignoring):\n{err.stderr}\n")
I see. But I still think that the code is more readable this way. (I'll change the comment later)

2021-08-10 12:21 UTC, maringuu commented on src/install/common.py
> -        dnf_install_packages('python3-ssdeep')
According to @any333 the reasoning was that pip had some problems on fedora.
My guess is that the problems probably do not exists anymore.

2021-08-11 09:09 UTC, jstucke approved these changes

2021-08-11 09:09 UTC, jstucke commented on .pre-commit-config.yaml
> -
this needs to be added back before the merge :sweat_smile:

2021-08-11 12:51 UTC, dorpvom requested changes

2021-08-11 12:51 UTC, dorpvom commented on src/helperFunctions/install.py
> +        subprocess.run(cmd_, capture_output=True, encoding='UTF-8', shell=shell, check=True, **kwargs)
This still isn't py < 3.7 compatible
```
14:48:11 [2021-08-11 14:48:11][install][INFO]: Running: sudo -EH pip3 install -r ./requirements_common.txt
14:48:11 Traceback (most recent call last):
14:48:11   File "./src/install.py", line 197, in <module>
14:48:11     install()
14:48:11   File "./src/install.py", line 171, in install
14:48:11     common(distribution)
14:48:11   File "/home/jenkins/workspace/bionic/src/install/common.py", line 37, in main
14:48:11     run_cmd_with_logging("sudo -EH pip3 install -r ./requirements_common.txt")
14:48:11   File "/home/jenkins/workspace/bionic/src/helperFunctions/install.py", line 224, in run_cmd_with_logging
14:48:11     subprocess.run(cmd_, capture_output=True, encoding='UTF-8', shell=shell, check=True, **kwargs)
14:48:11   File "/usr/lib/python3.6/subprocess.py", line 423, in run
14:48:11     with Popen(*popenargs, **kwargs) as process:
14:48:11 TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

2021-08-13 07:38 UTC, jstucke commented on src/install/common.py
> -        dnf_install_packages('python3-ssdeep')
according to @dorpvom, the problems still exists and we still need this for fedora

2021-08-13 10:48 UTC, maringuu commented on src/install/common.py
> -        dnf_install_packages('python3-ssdeep')
Added the `ssdep-devel` dependency for fedora so the build should now succeed.

2021-08-18 10:56 UTC, dorpvom approved these changes

2021-08-18 11:05 UTC, merged