objects/firmware: Document Firmware
fkie-cad/FACT_core pull request #619
Opened 2021-08-03 14:26 UTC by maringuu

2021-08-06 10:25 UTC, rhelmke requested changes

2021-08-06 10:25 UTC, rhelmke commented on src/objects/firmware.py
> +        self.part: str = ''
Overall, I'd like a little bit less verbosity, more explanation, and clearer definitions in your comments. To clarify what I mean by that, below a little example :-)

```suggestion
        #: Specifies the parts of an embedded system that are contained in the firmware.
        #: While this meta data string can be freely defined during firmware upload,
        #: FACT provides a preset of frequently used values: 'complete', 'kernel', ' bootloader', and 'root-fs'.
        #: The firmware image is assumed to be 'complete' if the assigned value is an empty string.
        self.part: str = ''
```

2021-08-06 10:25 UTC, rhelmke commented on src/objects/firmware.py
I understand that the setters below are self-explanatory (and additionally wonder why the trivial ones exist).
Yet, a proper Docstring for all methods would still be nice for the Sphinx documentation.

2021-08-20 07:47 UTC, rhelmke commented on src/objects/firmware.py
> +    It esentially is a FileObject with some more attributes that only make
*essentially :-). But how about this?

```suggestion
    It is a specialization of :meth:`objects.file.FileObject that adds a variety of firmware-specific attributes.
```

2021-08-20 07:52 UTC, rhelmke requested changes
Looks better. :-) Please apply the requested changes and I can approve.

2021-08-20 07:52 UTC, rhelmke commented on src/objects/firmware.py
> +        Additionally `self` is set to be the root file of the fimware.
This is an implementation detail that is irrelevant here.
```suggestion
```

2021-08-20 08:37 UTC, maringuu commented
> Please apply the requested changes

Done.

2021-08-20 09:06 UTC, rhelmke approved these changes

2021-09-10 09:24 UTC, maringuu commented
Fixed the typo, the CI works now.

2021-09-13 11:21 UTC, jstucke reviewed
The Firmware docs look pretty good now :smile: 
Two small issues:

2021-09-13 11:21 UTC, jstucke commented on src/objects/firmware.py
> +        #: This attribute is **optional** and may be `None`.
It would be good to add the info that it is automatically set to `'1970-01-01'` if it is empty

2021-09-13 11:21 UTC, jstucke commented on src/objects/firmware.py
>          self.device_name: str = None
The optional parameters should use the type `Optional[]` from `typing` (i.e. `Optional[str]` here)

2021-09-13 11:46 UTC, jstucke approved these changes

2021-09-14 06:12 UTC, merged