Fix session recycling
fkie-cad/FACT_core pull request #816
Opened 2022-07-08 10:45 UTC by jstucke

Multiple worker threads in the frontend used the same DB interface instances and with that the same sessions which caused errors. This PR moves the DB engine to its own class so that the frontend can use different instances of the DB interfaces.

2022-07-11 10:03 UTC, rhelmke requested changes

2022-07-12 08:32 UTC, jstucke commented on src/helperFunctions/database.py
> +DbInterface = TypeVar('DbInterface')
fixed. Also added `ContextManager[]` so that PyCharm is able to correctly determine the returned type

2022-07-14 11:44 UTC, rhelmke requested changes
Found some more generic usage of `with get_shared_session(...) as db`

2022-07-14 11:44 UTC, rhelmke commented on src/web_interface/components/ajax_routes.py
> +                root = [convert_to_jstree_node(node)]
```suggestion
        with get_shared_session(self.db.frontend) as frontend_db:
            for node in frontend_db.generate_file_tree_level(uid, root_uid):  # only a single item in this 'iterable'
                root = [convert_to_jstree_node(node)]
```

2022-07-14 11:44 UTC, rhelmke commented on src/web_interface/rest/rest_compare.py
> +                result = db.get_comparison_result(compare_id)
```suggestion
        with get_shared_session(self.db.comparison) as comparison_db:
            if comparison_db.comparison_exists(compare_id):
                result = comparison_db.get_comparison_result(compare_id)
```

2022-07-14 11:44 UTC, rhelmke commented on src/web_interface/rest/rest_compare.py
> +                )
```suggestion
        with get_shared_session(self.db.comparison) as comparison_db:
            if comparison_db.comparison_exists(compare_id) and not data['redo']:
                return error_message(
                    'Compare already exists. Use "redo" to force re-compare.',
                    self.URL, request_data=request.json, return_code=200
                )
```

2022-07-15 11:05 UTC, merged