Run pyupgrade
fkie-cad/FACT_core pull request #840
Opened 2022-08-16 13:54 UTC by maringuu

For future reference:
```sh
pyupgrade --py37-plus $(git ls-tree -r --name-only master| rg "\.py$")
```
Four files need manual fixing as pyupgrade does not insert blank lines sometimes when needed.

I'm not sure if 3.7+ is the right python version. What version are we currently supporting?

2022-09-27 13:21 UTC, jstucke requested changes
I didn't know `pyupgrade` until now and it seems to be really useful.

> I'm not sure if 3.7+ is the right python version. What version are we currently supporting?

Generally all stable versions (so 3.7 to 3.10 at the moment and also 3.11 soon)

> Four files need manual fixing as pyupgrade does not insert blank lines sometimes when needed.

Do they still need fixing? Which files?

2022-09-27 13:21 UTC, jstucke commented on src/plugins/analysis/known_vulnerabilities/docker/scripts/detect_CVE-2021-45608.py
> -                    print('found __kmalloc call @ {}'.format(ref.getFromAddress()))
this file is a Ghidra / jython script and cannot be upgraded in this way (which is also the reason the tests fail in the CI)

2022-10-04 10:57 UTC, maringuu commented
I reran everything ontop of master.

> Do they still need fixing? Which files?

Now this pr is split in two commits. The second fixes the files.

> This is also a ghidra script and cannot be upgraded this way

Oh of course.

2022-10-13 12:47 UTC, jstucke approved these changes

2022-10-17 14:05 UTC, merged