Replace asserts
fkie-cad/FACT_core pull request #916
Opened 2022-12-01 15:36 UTC by maringuu

Preliminary work for my incoming rework of the tests.

2022-12-01 15:41 UTC, maringuu commented on src/plugins/analysis/string_evaluation/test/test_string_eval.py
> +        ], 'Fehler beim bewerten'
Err I don't think we should have german comments in our code.
I'll fix this in a future PR.

2022-12-01 16:18 UTC, jstucke requested changes
Not all tests were translated correctly into the new format

2022-12-01 16:18 UTC, jstucke commented on src/test/unit/helperFunctions/test_uid.py
> +        assert [self.test_uid], 'uid list not recognized'
I'm pretty sure this was wrong all the time :rofl: 
```suggestion
        assert is_list_of_uids([self.test_uid]), 'uid list not recognized'
```

2022-12-01 16:18 UTC, jstucke commented on src/test/unit/helperFunctions/test_yara_binary_search.py
> +        assert test_dict, {1: [1, 2, 3], 2: [1, 2 == 3]}
.

2022-12-01 16:18 UTC, jstucke commented on src/test/unit/scheduler/test_compare.py
> +        ), 'none existing should always be done'
I'm not even sure what the message should tell us ... and it should probably be "non-existing"

2022-12-06 13:18 UTC, maringuu commented on src/plugins/analysis/string_evaluation/test/test_string_eval.py
> +        assert result_false == 0, 'Mail false-positive'
Yeah out of scope. Lets to such refactoring after #895 is finished.

2022-12-06 14:10 UTC, maringuu commented
A addressed all your comments since the fixes were so leightweight.

2022-12-07 16:25 UTC, merged