Minor test improvements
fkie-cad/FACT_core pull request #940
Opened 2022-12-28 12:00 UTC by maringuu

2022-12-29 08:53 UTC, maringuu commented
https://github.com/fkie-cad/FACT_core/actions/runs/3793900286

2022-12-29 08:57 UTC, maringuu commented
https://github.com/fkie-cad/FACT_core/actions/runs/3799434870

2023-01-06 08:59 UTC, jstucke requested changes
Looks good apart from some small stuff

2023-01-06 08:59 UTC, jstucke commented on src/conftest.py
> +    dir = tempfile.mkdtemp(prefix='fact-docker-mount-base-dir')
`dir` is a python builtin and should not be used

```suggestion
    tmp_dir = tempfile.mkdtemp(prefix='fact-docker-mount-base-dir')
```

2023-01-06 08:59 UTC, jstucke commented on src/conftest.py
> +    os.chmod(dir, 0o770)
This part seems to be mostly the same as what happens at the beginning of the `main()` method in `src/start_fact_backend.py`. Would it make sense to put it in a helper function (in fileSystem.py or docker.py maybe)?

2023-01-10 12:07 UTC, jstucke approved these changes

2023-01-10 12:41 UTC, maringuu commented
https://github.com/fkie-cad/FACT_core/actions/runs/3883411072

2023-01-10 13:38 UTC, merged